workflows:
  aura-music-android:
    name: Aura Music - APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Créer assets
        script: |
          mkdir -p assets/images
          mkdir -p assets/animations
      - name: Dependencies
        script: flutter pub get
       - name: Construire l'APK Release
        script: flutter build apk --release --no-tree-shake-icons

    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dianesekachrist@gmail.com
        notify:
          success: true
          failure: true
